# Dobot M1 arm orientation
port: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A107R2E8-if00-port0"

# Dobot Default PTP CP JOG Param
vel: 50.0 # default velocity ratio of dobot M1
acc: 50.0 # defaulr acceleration ratio of dobot M1
