# Dobot M1 arm orientation
port: "/dev/ttyUSB0"
arm_orient: "LeftyArmOrientation" # "RightyArmOrientation"
vel: 50.0 # default velocity ratio of dobot M1
acc: 50.0 # defaulr acceleration ratio of dobot M1